# Generated by Django 6.0.6 on 2026-07-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
