# Generated by Django 6.0.6 on 2026-07-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodID', models.BigAutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
