# Generated by Django 6.0.6 on 2026-08-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('task', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
