# Generated by Django 6.0.6 on 2026-07-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'cust_table',
            },
        ),
    ]
