# Generated by Django 6.0.6 on 2026-07-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sub1', models.FloatField()),
                ('sub2', models.FloatField()),
            ],
        ),
    ]
