# Generated by Django 6.0.6 on 2026-07-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eno', models.BigAutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('hra', models.FloatField()),
            ],
        ),
    ]
