# Generated by Django 6.0.6 on 2026-07-13 14:27

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
