# Generated by Django 6.0.6 on 2026-07-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
    ]
