# Generated by Django 6.0.6 on 2026-07-14 14:32

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employee_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
