# Generated by Django 6.0.6 on 2026-08-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('fee', models.FloatField()),
            ],
        ),
    ]
