# Generated by Django 6.0.6 on 2026-08-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employess',
            fields=[
                ('eid', models.BigAutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=20)),
                ('sal', models.FloatField()),
            ],
        ),
    ]
