# Generated by Django 6.0.6 on 2026-08-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employess',
            name='job',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
