# Generated by Django 6.0.6 on 2026-07-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('uname', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=7)),
                ('role', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=15)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
