# Generated by Django 6.0.6 on 2026-07-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
