# Generated by Django 6.0.6 on 2026-06-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolno', models.IntegerField()),
                ('sub1', models.FloatField()),
                ('sub2', models.FloatField()),
            ],
            options={
                'db_table': 'marks',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rolno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
