# Generated by Django 6.0.6 on 2026-06-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
