# Generated by Django 6.0.6 on 2026-07-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
